name: fit_ui
description: A powerful and intuitive Flutter package for creating responsive and adaptive UIs. Build component-level responsive layouts with ease.
version: 1.0.2
homepage: https://github.com/mehrdadmoradi001/fit_ui
repository: https://github.com/mehrdadmoradi001/fit_ui
issue_tracker: https://github.com/mehrdadmoradi001/fit_ui/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


# The topics are used by pub.dev to categorize your package and make it more discoverable.
topics:
  - responsive
  - adaptive
  - layout
  - flutter-ui
  - breakpoint